apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels: 
    app: jboxer
  name: jboxer
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jboxer
  template:
    metadata:
      labels:
        app: jboxer
    spec:
      volumes:
      - name: key-volume
        secret:
          secretName: keyfile
      containers:
      - name: jboxer
        image: sashosot/wildfly:14.0
        volumeMounts:
        - name: key-volume
          mountPath: /opt/certificates/
        env:
          - name: WILDFLY_USER
            valueFrom:
              secretKeyRef:
                name: logtext
                key: username
          - name: WILDFLY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: logtext
                key: password        
        ports:        
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP 
        readinessProbe:
          failureThreshold: 2
          httpGet:
            httpHeaders:
            - name: Host
              value: localhost
            path: /
            port: https
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 10

        
