kind: Service
apiVersion: v1
metadata:
  name: jboxer-service
spec:
  selector:
    app: jboxer
  ports:  
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  type: LoadBalancer
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
