apiVersion: v1
kind: Pod
    spec:
      containers:
      - name: wildfly
    image: sashosot/wildfly:14.0
    env:
      - name: WILDFLY_USER
        valueFrom:
          secretKeyRef:
        name: logtext
        key: username
      - name: WILDFLY_PASSWORD
        valueFrom:
          secretKeyRef:
        name: logtext
        key: password
    volumeMounts:
    - name: key-volume
      mountPath: /opt/certificate/javakeystore.jks
      readOnly: true
      volumes:
      - name: key-volume
    secret:
      secretName: keyfile
    restartPolicy: Never

